server:
  port: 9006
spring:
  application:
    name: hrm-page
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm_page
    username: root
    password: 666888
mybatis-plus:
  mapper-locations: classpath:com/yuhang/hrm/mapper/*Mapper.xml
  type-aliases-package: com.yuhang.hrm.domain,com.yuhang.hrm.query